const ACTIONS = {
  LOGIN: "LOGIN",
  GET_TOKEN: "GET_TOKEN",
  GET_USER: "GET_USER",
  GET_ALL_USERS: "GET_ALL_USERS",
  LOGOUT: "LOGOUT",
  TURN_ON_LOADING: "TURN_ON_LOADING",
  TURN_OFF_LOADING: "TURN_OFF_LOADING",
};

export default ACTIONS;
